//Teste de Requisições REST - PRODUTOS E PEDIDOS
@baseURL = http://localhost:4000/api

// GET - Lista todos os Produtos
GET {{baseURL}}/produtos
Content-Type: application/json


###
// POST - Insere um novo Produtos*/
POST {{baseURL}}/produtos
Content-Type: application/json

{ 
    "nome": "play",
    "preco": 28500,
    "status": "disponivel"     
}

###
// PUT - Altera o produto
PUT {{baseURL}}/produtos
Content-Type: application/json

{
      
    "nome": "play",
    "preco": 28500,
    "status": "disponivel"
}


###
// DELETE - Apaga um produto pelo nome
DELETE {{baseURL}}/produtos/play
Content-Type: application/json